# Generated by Django 2.1.3 on 2018-12-20 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('serial', models.IntegerField()),
                ('key_pem', models.TextField()),
                ('csr_pem', models.TextField()),
                ('cert_pem', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('next_serial', models.IntegerField()),
                ('key_pem', models.TextField()),
                ('csr_pem', models.TextField()),
                ('cert_pem', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='ca.CertificateAuthority'),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('certificate_authority', 'serial')},
        ),
    ]
